services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: olimpia_database
    volumes:
      - ./postgres:/var/lib/postgresql/data
#   pgAdmin:
#     depends_on:
#       - db
#     image: dpage/pgadmin4:8.6
#     volumes:
#       - ./pgadmin:/var/lib/pgadmin
#     ports:
#       - "8080:80"
#     environment:
#       - PGADMIN_DEFAULT_PASSWORD=123456
#       - PGADMIN_DEFAULT_EMAIL=olimpiagh1s@google.com
#     restart: always


services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - '5433-5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: olimpia_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    